# Generated by Django 3.1.5 on 2021-01-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_genres',
            old_name='publisher',
            new_name='genre',
        ),
    ]
